base_url = "https://ktsh.vercel.app"
title = "Shree Kottes"
description = "My digital space in some corner of the Internet"
default_language = "en"

generate_feed = true
feed_filename = "rss.xml"
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
           {name = "tags", rss = true}
]

compile_sass = true

build_search_index = false

[markdown]
render_emoji = true 
smart_punctuation = true 

[extra]
home_subtitle = "Learning to build things."
footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

main_menu = [
    { link = "/", name = "/home" },
    { link = "/blog", name = "/blog" },
    { link = "/about", name = "/about" },
    { link = "/resume", name = "/resume" }
]

socials = [
    { name = "twitter", link = "https://twitter.com/shreekottes" },
    { name = "github", link = "https://github.com/kottesh" },
    { name = "email", link = "mailto:kottezh@gmail.com" },
    { name = "linkedin", link = "https://linkedin.com/in/shreekottes" }
]

[extra.highlightjs]
enable = true
clipboard = false 
theme = "ros-pine"

[extra.author]
name = "ktsh.in"
email = "kottezh@gmail.com"

